### ISSUE TITLE
Angular 2 Font Awesome update

### ISSUE THREAD

**Issue by baruchvlz** [Synerty/peek-mobile-util#1]
Hello,

I'm the author for `angular2-font-awesome` I saw this repo had a dependency on the library just wanted to let you know there has been an update to the library. I suggest changing your dependency to `"angular-font-awesome": "^2.0.0"` or set it to `"angular2-font-awesome" : "1.2.0"` that way it doesn't try to use the latest version.

Edit:
If you use 2.0.0 there has been changes on how to use the library as well, please revisit the [repo](https://github.com/baruchvlz/angular-font-awesome) to see the instructions in the readme file.

Cheers.

**Comment by jarrodchesney** [comment]
Thanks, I've updated to 2.0
